# Generated by Django 3.1.6 on 2022-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='Udated_At',
            new_name='Updated_At',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
