# Generated by Django 3.1.6 on 2022-01-13 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Allmodels', '0002_auto_20220113_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Created_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
