# Generated by Django 3.1.6 on 2022-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allmodels', '0003_auto_20220113_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_At',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Updated_At',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='created_At',
            field=models.DateField(auto_now_add=True),
        ),
    ]
